version: 0
os: linux
files:
    - source: /
      destination: /home/ubuntu/user-app
      overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/user-app
      owner: ubuntu
      group: ubuntu
      mode: 755

hooks:
    AfterInstall:
        - location: ./scripts/after-deploy.sh
          # runas: ubuntu
